@baseUrl = http://localhost:3333
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjV4V1JhcVAzalhydW5BaUVKWnRReSJ9.eyJpc3MiOiJodHRwczovL2Rldi1pZ25pdGUtbGFiLTAxLWp1bGlvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMTU3Mzc3MTg5Mzc0OTUzNDk3NiIsImF1ZCI6WyJpZ25pdGUtbGFiLTAxLWF1dGgiLCJodHRwczovL2Rldi1pZ25pdGUtbGFiLTAxLWp1bGlvLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTYzODc5OTMsImV4cCI6MTcxNjQ3NDM5Mywic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImF6cCI6ImkxZmlmR2d6MkhmZVI3TXVZRG90MW5ZbmtCd2tjZkJmIn0.Fw4MQzfYlyIXsixJTozYYbtIn_hrPtL5pLwHQaprTLRjwsM1nOnGYTh3N1EFbhVPqpou-iO3rval5vvX02IVrAwbKivbTVpFl63CRbKt2XoZQaqldUA4ziQFDjP61YhdeusrOPHBVXbDJF7uC7RJ4T-s-Usni7Exz2n4p93y4M9Sr91zbzN4Undt94U6Par-4VgltDL39DshoMpluUmMpiIJNFZTzKi9Hk8LBAOGtSwOsFYdF4TDVpSXDAu3vYN8O7TX11tb6O5K_MExR2lSisKu8nqM8bPDFpM5s2TyrR1w0NBTZIqTfmL6lHlgkXjKKIeKIRIa857pWlztTMyfgQ

# @name test
GET {{baseUrl}}/test
Authorization: Bearer {{accessToken}}